server:
  port: 8085

spring:
  application:
    name: transfer
  main:
    banner-mode: off
  datasource:
    url: ${PG_URL}?currentSchema=transfer
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
    default-schema: "transfer"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}

      client:
        registration:
          transfer-service:
            provider: keycloak
            client-id: transfer-service
            client-secret: ${TRANSFER_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}

services:
  notifications:
    url: ${NOTIFICATIONS_URL}
  accounts:
    url: ${ACCOUNTS_URL:http}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true