server:
  port: 8081

spring:
  application:
    name: front
  main:
    banner-mode: off
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: front
            client-secret: XSaU8186LATDZHoaGW7siSlFfrrBlpRJ
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/realms/bank-app}

gateway:
  path: ${GATEWAY_PATH:http://localhost:8079/api}