apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-config
data:
  KEYCLOAK_URL: http://192.168.1.108:8080/realms/bank-app
  NOTIFICATIONS_URL: http://bank-notifications:8082
  ACCOUNTS_URL: http://bank-accounts:8084
  CASH_URL: http://bank-cash:8083
  TRANSFER_URL: http://bank-transfer:8085