apiVersion: v2
name: prometheus
description: Prometheus chart
version: "81.2.0"
dependencies:
  - name: kube-prometheus-stack
    version: "81.2.0"
    repository: "oci://ghcr.io/prometheus-community/charts"