server:
  port: 8079
spring:
  application:
    name: application-gateway
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/realms/bank-app}
  cloud:
    consul:
      host: ${CONSUL_URL:localhost}
      port: ${CONSUL_PORT:8500}
      config:
        enabled: true
        prefix: config
        defaultContext: application

services:
  accounts:
    url: ${ACCOUNTS_URL:http://localhost:8084}
  cash:
    url: ${CASH_URL:http://localhost:8083}
  transfer:
    url: ${TRANSFER_URL:http://localhost:8085}