server:
  port: 8079
spring:
  application:
    name: application-gateway
  main:
    banner-mode: off

services:
  accounts:
    url: ${ACCOUNTS_URL}
  cash:
    url: ${CASH_URL}
  transfer:
    url: ${TRANSFER_URL}