server:
  port: ${REST_PORT:8083}

spring:
  application:
    name: cash
  main:
    banner-mode: off
  datasource:
    url: ${PG_URL}?currentSchema=cash
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
    default-schema: "cash"
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topics:
        notifications: ${NOTIFICATIONS_TOPIC:notifications}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}

      client:
        registration:
          cash-service:
            provider: keycloak
            client-id: cash-service
            client-secret: ${CASH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}

services:
  notifications:
    url: ${NOTIFICATIONS_URL}
  accounts:
    url: ${ACCOUNTS_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true