server:
  port: ${REST_PORT:8083}

spring:
  application:
    name: cash
  main:
    banner-mode: off
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/bankdb}?currentSchema=cash
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
    default-schema: "cash"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/realms/bank-app}

      client:
        registration:
          cash-service:
            provider: keycloak
            client-id: cash-service
            client-secret: ${CASH_CLIENT_SECRET:Dj8JrrzsbMTx7b1kGpvS4O75whP2jkZI}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/realms/bank-app}

services:
  notifications:
    url: ${NOTIFICATIONS_URL:http://localhost:8082}
  accounts:
    url: ${ACCOUNTS_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true