server:
  port: 8084

spring:
  application:
    name: accounts
  main:
    banner-mode: off
  datasource:
    url: ${PG_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
#  sql:
#    init:
#      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/realms/bank-app}

      client:
        registration:
          accounts-service:
            provider: keycloak
            client-id: accounts-service
            client-secret: ${ACCOUNTS_CLIENT_SECRET:h8cQdPuY7ZyoSmzct39T3qumtP9yqVBL}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/realms/bank-app}

services:
  notifications:
    url: ${NOTIFICATIONS_URL:http://localhost:8082}

logging:
  level:
    root: DEBUG