apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-config
data:
  KEYCLOAK_URL: http://192.168.1.108:8080/realms/bank-app
  KAFKA_HOST: bank-kafka-broker:9092
  ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans