gateway:
  replicaCount: 1
  service:
    type: NodePort

cash:
  replicaCount: 2
  image:
    tag: latest

transfer:
  replicaCount: 2
  image:
    tag: latest

accounts:
  replicaCount: 2
  image:
    tag: latest

notifications:
  replicaCount: 2
  image:
    tag: latest
