gateway:
  replicaCount: 1
  service:
    type: NodePort

cash:
  replicaCount: 2
  image:
    tag: lasest

transfer:
  replicaCount: 2
  image:
    tag: lasest

accounts:
  replicaCount: 2
  image:
    tag: lasest

notifications:
  replicaCount: 2
  image:
    tag: lasest
