apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-config
data:
  PG_URL: "jdbc:postgresql://bank-postgresql:5432/bankdb"
  PG_USERNAME: postgres
  PG_PASSWORD: mysecretpassword
  KEYCLOAK_URL: http://192.168.1.108:8080/realms/bank-app
  NOTIFICATIONS_URL: http://bank-notifications:8082