livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

clusterName: "elasticsearch"
replicas: 1

resources:
  requests:
    cpu: "100m"
    memory: "750Mi"
  limits:
    cpu: "1000m"
    memory: "750Mi"

esJavaOpts: "-Xmx512m -Xms512m"
discovery:
  type: single-node

xpack:
  security:
    enabled: false

persistence:
  enabled: true
  storageClass: "standard"
  size: 1Gi

esConfig:
  elasticsearch.yml: |
    network.host: 0.0.0.0
