server:
  port: 8082

spring:
  application:
    name: notifications
  main:
    banner-mode: off
  config:
    import: "optional:classpath:application-chassis.yaml"
  kafka:
    bootstrap-servers: ${KAFKA_HOST:192.168.5.15:9095}
    consumer:
      group-id: bank-notifications-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring:
          json:
            trusted:
              packages: "*"
